default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: rosytl_user
  password: rosytl_password

development:
  <<: *default
  database: rosytl_development

test:
  <<: *default
  database: rosytl_test

production:
  url: <%= ENV['ROSYTL_URL'] %>
